### ISSUE TITLE
Compilation fails: error: only virtual member functions can be marked 'override' (JUCE incompatibility)

### ISSUE THREAD

**Issue by yurivict** [BespokeSynth/BespokeSynth#1047]
## Describe the bug

```
/usr/ports/audio/bespokesynth/work/BespokeSynth-f0a0e40/Source/MainComponent.cpp:167:47: error: only virtual member functions can be marked 'override'
                              int numSamples) override
                                              ^~~~~~~~
1 error generated.
```

Revision: f0a0e40
juce-7.0.3
clang-14
FreeBSD 13.1

**Comment by NoxyNixie** [comment]
Bespoke Nightly (main branch) is currently set up to compile with Juce 7.0.2 (which is the version in the submodule).

**Comment by dvzrv** [comment]
@yurivict in #1398 I'm fixing that (I hope).
