### ISSUE TITLE
build fail with latest pull

### ISSUE THREAD

**Issue by davephillips** [BespokeSynth/BespokeSynth#15]
Ubuntu 18.04
GCC 7.5.0

Lots of errors with the Python stuff, e.g. :

```
../../Source/pybind11/cast.h:1247:53: error: ‘PyString_Size’ was not declared in this scope
         size_t length = (size_t) PYBIND11_BYTES_SIZE(utfNbytes.ptr()) / sizeof(CharT);
...
/usr/include/python2.7/object.h:769:24: error: ‘PyObject {aka struct _object}’ has no member named ‘ob_refcnt’
     ((PyObject*)(op))->ob_refcnt++)
...
../../Source/pybind11/detail/class.h:493:15: error: ‘Py_buffer {aka struct bufferinfo}’ has no member named ‘len’
         view->len *= s;
               ^~~
```

Are you using Python2 or Python3 ?

**Comment by awwbees** [comment]
so far I've gotten it working with Python 2.7 on OS X and Python 3.8 on Windows, I haven't attempted to build on Linux yet. you might be able to figure out what's wrong by looking at the setup steps in the pybind11 docs. it seems like @KottV has gotten things running on linux, judging by issue #14

**Comment by KottV** [comment]
Ok, I've commented:

//#define ssize_t ssize_t_undef_hack
and
//#undef ssize_t

in ScriptStatus.cpp and ScriptModule.cpp

and was able to compile

Sadly I don't know how to quick test that script module is working and there no "paste" (in Linux at least).
Can you provide couple of lines which I'll put for testing?

**Comment by KottV** [comment]
well, it do something, that is in console output:

> python execution exception (error_already_set): AttributeError: 'module' object has no attribute 'schedule_note'

**Comment by awwbees** [comment]
ah, that ssize_t stuff was necessary for windows, but apparently breaks other platforms so I'll guard it.

I'll fix up keybindings to work properly in windows/linux, right now paste is hardcoded to "command-V" (the OSX shortcut)

a quick script to run would just be:
`this.play_note(60, 127, 1.0/16)`
which would send out pitch 60 at velocity 127 for a 16th note, when you hit the "run" button.

**Comment by KottV** [comment]
yep, it works

I think, we need "quick save" feature

**Comment by awwbees** [comment]
there is a well-hidden one: press tab to bring up the console, type 's', then hit enter. this will save the patch to "savestates/quicksave.bsk". then, if you later type 'l' into the console, it will load that quicksave file.

**Comment by KottV** [comment]
I see)

**Comment by davephillips** [comment]
@awwbees and @KottV - Thanks for the tips ! I can build it but now have a different problem (opened in a new thread).
